# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/fixed_array_field/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call

comptime uint8_t = UInt8

@fieldwise_init
struct faf_block(Copyable, Movable):
    var bytes: Array[uint8_t, 4]
