# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/nested_flexible_tail_terminal/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

comptime uint32_t = UInt32

@align(4)
struct nft_packet_tail:
    var len: uint32_t
    var payload: Array[c_uchar, 0]
    @staticmethod
    def payload_offset() -> UInt:
        return 4
    @staticmethod
    def payload_ptr(base: Pointer[nft_packet_tail, ImmUntrackedOrigin]) -> Pointer[c_uchar, ImmUntrackedOrigin]:
        var raw = rebind[Pointer[c_uchar, ImmUntrackedOrigin]](base)
        return raw.unsafe_offset(4)
    @staticmethod
    def payload_mut_ptr(base: Pointer[nft_packet_tail, MutUntrackedOrigin]) -> Pointer[c_uchar, MutUntrackedOrigin]:
        var raw = rebind[Pointer[c_uchar, MutUntrackedOrigin]](base)
        return raw.unsafe_offset(4)

@align(4)
struct nft_packet_wrapper:
    var tag: uint32_t
    var tail: nft_packet_tail
    @staticmethod
    def payload_offset() -> UInt:
        return 8
    @staticmethod
    def payload_ptr(base: Pointer[nft_packet_wrapper, ImmUntrackedOrigin]) -> Pointer[c_uchar, ImmUntrackedOrigin]:
        var raw = rebind[Pointer[c_uchar, ImmUntrackedOrigin]](base)
        return raw.unsafe_offset(8)
    @staticmethod
    def payload_mut_ptr(base: Pointer[nft_packet_wrapper, MutUntrackedOrigin]) -> Pointer[c_uchar, MutUntrackedOrigin]:
        var raw = rebind[Pointer[c_uchar, MutUntrackedOrigin]](base)
        return raw.unsafe_offset(8)
