# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/non_register_return_stub/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call

comptime int32_t = Int32

@align(4)
@fieldwise_init
struct nrr_payload(Copyable, Movable):
    var values: Array[int32_t, 2]

def nrr_build() abi("C") -> nrr_payload:
    return external_call["nrr_build", nrr_payload]()
