# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/opaque_forward_ptrs/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call

struct ofp_handle(Copyable, Movable):
    pass

def ofp_open() abi("C") -> Optional[Pointer[ofp_handle, MutUntrackedOrigin]]:
    return external_call["ofp_open", Optional[Pointer[ofp_handle, MutUntrackedOrigin]]]()

def ofp_close(handle: Optional[Pointer[ofp_handle, MutUntrackedOrigin]]) abi("C") -> None:
    external_call["ofp_close", NoneType, Optional[Pointer[ofp_handle, MutUntrackedOrigin]]](handle)
