# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/macro_cast_expressions/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import c_int, c_uint, c_ulong_long

comptime __u32 = c_uint

comptime __u64 = c_ulong_long

comptime IORING_TIMESTAMP_HW_SHIFT = c_int(16)

comptime IORING_TIMESTAMP_TYPE_SHIFT = c_int(17)

comptime IORING_CQE_F_TSTAMP_HW = c_uint(65536)

comptime IORING_ZCRX_AREA_SHIFT = c_int(48)

comptime IORING_ZCRX_AREA_MASK = c_ulong_long(18446462598732840960)
