# Generated by mojo_bindgen - do not edit by hand.
# source: tests/surface/fixtures/global_stub_const_ptr/input.h
# library: surface_globals  link_name: surface_globals
# FFI mode: external_call

from std.ffi import external_call, DEFAULT_RTLD, OwnedDLHandle, _DLHandle, _Global, _get_global
from std.memory.unsafe_pointer import unsafe_cast
from std.os import abort

comptime _BINDGEN_LIB_NAME = "surface_globals"
comptime _BINDGEN_LINK_NAME = "surface_globals"

def _bindgen_init_dylib() -> OwnedDLHandle:
    try:
        return OwnedDLHandle(DEFAULT_RTLD)
    except e:
        abort(t"bindgen: failed to open process dynamic symbol table: {e}")

comptime _BINDGEN_DYLIB = _Global["mojo_bindgen/surface_globals", _bindgen_init_dylib]

# Returns a borrowed process-lifetime dynamic library handle; do not close it.
def _bindgen_dylib() -> _DLHandle:
    var dylib_ptr = _get_global[
        _BINDGEN_DYLIB.name,
        _BINDGEN_DYLIB._init_wrapper,
        _BINDGEN_DYLIB._deinit_wrapper,
    ]()
    var dylib = unsafe_cast[Type=_BINDGEN_DYLIB.StorageType](dylib_ptr).value()[].borrow()
    if not dylib:
        abort(t"bindgen: failed to load dynamic library '{_BINDGEN_LIB_NAME}'")
    return dylib

def _bindgen_function[Fn: TrivialRegisterPassable](symbol: StringSpan) -> Fn:
    var fn_ptr = _bindgen_dylib().get_symbol[NoneType](symbol)
    if not fn_ptr:
        abort(
            t"bindgen: missing C function symbol '{symbol}' "
            t"in dynamic library '{_BINDGEN_LIB_NAME}'"
        )
    return Pointer(to=fn_ptr.value()).unsafe_bitcast[Fn]()[]

struct GlobalVar[T: Copyable & Deinitable, //, link: StaticString]:
    @staticmethod
    def _raw() -> Pointer[Self.T, MutUntrackedOrigin]:
        var opt: Optional[Pointer[Self.T, MutUntrackedOrigin]] = _bindgen_dylib().get_symbol[Self.T](StringSpan(Self.link))
        if not opt:
            abort(
                t"bindgen: missing C global symbol '{Self.link}' "
                t"in dynamic library '{_BINDGEN_LIB_NAME}'"
            )
        return opt.value()

    @staticmethod
    def ptr() -> Pointer[Self.T, MutUntrackedOrigin]:
        return rebind[Pointer[Self.T, MutUntrackedOrigin]](Self._raw())

    @staticmethod
    def load() -> Self.T:
        return Self._raw()[].copy()

    @staticmethod
    def store(value: Self.T) -> None:
        var p = rebind[Pointer[Self.T, MutUntrackedOrigin]](Self._raw())
        p[] = value.copy()

struct GlobalConst[T: Copyable & Deinitable, //, link: StaticString]:
    @staticmethod
    def _raw() -> Pointer[Self.T, MutUntrackedOrigin]:
        var opt: Optional[Pointer[Self.T, MutUntrackedOrigin]] = _bindgen_dylib().get_symbol[Self.T](StringSpan(Self.link))
        if not opt:
            abort(
                t"bindgen: missing C global symbol '{Self.link}' "
                t"in dynamic library '{_BINDGEN_LIB_NAME}'"
            )
        return opt.value()

    @staticmethod
    def ptr() -> Pointer[Self.T, ImmUntrackedOrigin]:
        return rebind[Pointer[Self.T, ImmUntrackedOrigin]](Self._raw())

    @staticmethod
    def load() -> Self.T:
        return Self._raw()[].copy()

struct gscp_cfg(Copyable, Movable):
    pass

# global `gscp_default_cfg` -> Optional[Pointer[gscp_cfg, ImmUntrackedOrigin]]
comptime gscp_default_cfg = GlobalVar[T=Optional[Pointer[gscp_cfg, ImmUntrackedOrigin]], link="gscp_default_cfg"]
