"""Render Mojo sidecars that validate emitted record layout."""

from __future__ import annotations

from dataclasses import dataclass

from mojo_bindgen.analysis.lowering_support import field_mojo_name, record_by_decl_id, record_name
from mojo_bindgen.analysis.record_layout import analyze_record_layout
from mojo_bindgen.ir import Struct, Unit
from mojo_bindgen.mojo_ir import (
    BitfieldGroupMember,
    MojoModule,
    OpaqueStorageMember,
    StoredMember,
    StructDecl,
    StructKind,
)


@dataclass(frozen=True)
class LayoutCheck:
    label: str
    expression: str
    expected: int


@dataclass(frozen=True)
class LayoutRecordCheck:
    record_name: str
    checks: tuple[LayoutCheck, ...]


def collect_layout_record_checks(
    *,
    normalized_unit: Unit,
    mojo_module: MojoModule,
) -> tuple[LayoutRecordCheck, ...]:
    """Collect C-layout expectations for records that have emitted Mojo structs."""

    mojo_structs = {decl.name: decl for decl in mojo_module.decls if isinstance(decl, StructDecl)}
    record_map = record_by_decl_id(normalized_unit)
    checks: list[LayoutRecordCheck] = []

    for decl in normalized_unit.decls:
        if not isinstance(decl, Struct):
            continue
        record_check = _layout_record_check(decl, normalized_unit, mojo_structs, record_map)
        if record_check is not None:
            checks.append(record_check)
    return tuple(checks)


def _layout_record_check(
    decl: Struct,
    unit: Unit,
    mojo_structs: dict[str, StructDecl],
    record_map: dict[str, Struct],
) -> LayoutRecordCheck | None:
    if decl.is_union or not decl.is_complete:
        return None

    mojo_name = record_name(decl)
    mojo_decl = mojo_structs.get(mojo_name)
    if mojo_decl is None or mojo_decl.kind != StructKind.PLAIN:
        return None

    facts = analyze_record_layout(
        decl,
        target_abi=unit.target_abi,
        record_map=record_map,
    )
    if not facts.is_complete:
        return None

    checks = [
        LayoutCheck(
            label=f"{mojo_name}.size",
            expression=f"size_of[{mojo_name}]()",
            expected=facts.size_bytes,
        ),
    ]
    if facts.align_bytes is not None:
        checks.append(
            LayoutCheck(
                label=f"{mojo_name}.align",
                expression=f"align_of[{mojo_name}]()",
                expected=facts.align_bytes,
            )
        )

    if _is_opaque_storage_decl(mojo_decl):
        return LayoutRecordCheck(record_name=mojo_name, checks=tuple(checks))

    member_names = _member_names(mojo_decl)
    for field_fact in facts.plain_fields:
        field = decl.fields[field_fact.index]
        member_name = field_mojo_name(field, field_fact.index)
        if member_name not in member_names:
            continue
        checks.append(
            LayoutCheck(
                label=f"{mojo_name}.{member_name}.offset",
                expression=f"r.field_offset[index={field_fact.index}]()",
                expected=field_fact.byte_offset,
            )
        )

    for run in facts.bitfield_runs:
        if run.name not in member_names:
            continue
        checks.append(
            LayoutCheck(
                label=f"{mojo_name}.{run.name}.offset",
                expression=f"r.field_offset[index={run.first_index}]()",
                expected=run.byte_offset,
            )
        )

    return LayoutRecordCheck(record_name=mojo_name, checks=tuple(checks))


def _is_opaque_storage_decl(decl: StructDecl) -> bool:
    return len(decl.members) == 1 and isinstance(decl.members[0], OpaqueStorageMember)


def _member_names(decl: StructDecl) -> set[str]:
    names: set[str] = set()
    for member in decl.members:
        if isinstance(member, StoredMember):
            names.add(member.name)
        elif isinstance(member, BitfieldGroupMember):
            names.add(member.storage_name)
        elif isinstance(member, OpaqueStorageMember):
            names.add(member.name)
        else:
            names.add(member.name)
    return names


def render_layout_test_module(
    *,
    normalized_unit: Unit,
    mojo_module: MojoModule,
    main_module_name: str,
    use_test_suite: bool = False,
) -> str:
    """Render a standalone Mojo file that asks Mojo for emitted record layout."""

    checks = collect_layout_record_checks(
        normalized_unit=normalized_unit,
        mojo_module=mojo_module,
    )
    lines = [
        "# Generated by mojo_bindgen - do not edit by hand.",
        f"# layout tests for: {main_module_name}",
        "",
        "from std.sys.info import align_of, size_of",
        "from std.reflection import reflect",
    ]
    if use_test_suite:
        lines.append("from std.testing import assert_equal, TestSuite")
    if checks:
        imported = ", ".join(record.record_name for record in checks)
        lines.append(f"from {main_module_name} import {imported}")

    if not use_test_suite:
        lines.extend(
            [
                "",
                "",
                "def _check_eq(label: String, got: Int, expected: Int) raises:",
                "    if got != expected:",
                '        raise Error(label + ": got " + String(got) + ", expected " + String(expected))',
            ]
        )

    for record in checks:
        lines.extend(["", "", f"def test_layout_{record.record_name}() raises:"])
        lines.append(f"    comptime r = reflect[{record.record_name}]()")
        for check in record.checks:
            if use_test_suite:
                lines.append(
                    f'    assert_equal(Int({check.expression}), {check.expected}, msg="{check.label}")'
                )
            else:
                lines.append(
                    f'    _check_eq("{check.label}", Int({check.expression}), {check.expected})'
                )
        if not record.checks:
            lines.append("    pass")

    lines.extend(["", "", "def main() raises:"])
    if use_test_suite:
        lines.append("    TestSuite.discover_tests[__functions_in_module()]().run()")
    else:
        if checks:
            for record in checks:
                lines.append(f"    test_layout_{record.record_name}()")
        else:
            lines.append("    pass")
    return "\n".join(lines) + "\n"


__all__ = [
    "LayoutCheck",
    "LayoutRecordCheck",
    "collect_layout_record_checks",
    "render_layout_test_module",
]
